### ISSUE TITLE
Sourceforge

### ISSUE THREAD

**Issue by andysavage** [DirectSponsor/DS#5]
I had a look at Sourceforge, with a view to the future open sourcing (?) of the project. It seems to duplicate everything here, but with a lot more features. It looks quite complicated, but I noticed you can import repositories from github to there, so no worries. 

So, a couple of questions:
* Is it best to keep using this as long as possible because it's straightforward and we don't need the complexity of Sourceforge yet?
* Can we run an open source project from here?
* If yes, would it be significantly better (in terms of attracting devs to work on the open source project) on Sourceforge?

**Comment by andysavage** [comment]
After thinking about it, a partial answer came. It looks like we'd need both, Sourceforge for the open source and github for ongoing dev specifically for directsponsor.org

**Comment by McGarryIT** [comment]
I don't know much about SoureForge so I googled.
Sounds like GitHub is the place to be.
Here's the link https://blog.idrsolutions.com/2014/03/top-5-free-hosted-version-control-sites-compared/

**Comment by andysavage** [comment]
Thanks for that! So it seems the distinction was in my own mind only. I was under the impression that SourceForge was the place for open-source stuff. Turns out it was a while back, but now there's quite a choice. 

So we can do all we need here. I'm relieved because SourceForge looks quite difficult to navigate and use. I'm trying to get my head around how it will work. We'll need a working version of the code to use in directsponsor.org, and then there will be other versions with changes to suit different purposes. Is that what forks are for?

**Comment by andysavage** [comment]
Closing this now. This link form Paul pretty much sews it up for me. We don't need to go beyond github for the open-source work. 
http://helb.github.io/goodbye-sourceforge/
